# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/emilh/workspace/physics_sim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/emilh/workspace/physics_sim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emilh/workspace/physics_sim/CMakeFiles /home/emilh/workspace/physics_sim//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emilh/workspace/physics_sim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/emilh/workspace/physics_sim/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pastasim

# Build rule for target.
pastasim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pastasim
.PHONY : pastasim

# fast build rule for target.
pastasim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/build
.PHONY : pastasim/fast

src/application.o: src/application.cpp.o
.PHONY : src/application.o

# target to build an object file
src/application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/application.cpp.o
.PHONY : src/application.cpp.o

src/application.i: src/application.cpp.i
.PHONY : src/application.i

# target to preprocess a source file
src/application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/application.cpp.i
.PHONY : src/application.cpp.i

src/application.s: src/application.cpp.s
.PHONY : src/application.s

# target to generate assembly for a file
src/application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/application.cpp.s
.PHONY : src/application.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sim_engine_device.o: src/sim_engine_device.cpp.o
.PHONY : src/sim_engine_device.o

# target to build an object file
src/sim_engine_device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/sim_engine_device.cpp.o
.PHONY : src/sim_engine_device.cpp.o

src/sim_engine_device.i: src/sim_engine_device.cpp.i
.PHONY : src/sim_engine_device.i

# target to preprocess a source file
src/sim_engine_device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/sim_engine_device.cpp.i
.PHONY : src/sim_engine_device.cpp.i

src/sim_engine_device.s: src/sim_engine_device.cpp.s
.PHONY : src/sim_engine_device.s

# target to generate assembly for a file
src/sim_engine_device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/sim_engine_device.cpp.s
.PHONY : src/sim_engine_device.cpp.s

src/sim_pipeline.o: src/sim_pipeline.cpp.o
.PHONY : src/sim_pipeline.o

# target to build an object file
src/sim_pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/sim_pipeline.cpp.o
.PHONY : src/sim_pipeline.cpp.o

src/sim_pipeline.i: src/sim_pipeline.cpp.i
.PHONY : src/sim_pipeline.i

# target to preprocess a source file
src/sim_pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/sim_pipeline.cpp.i
.PHONY : src/sim_pipeline.cpp.i

src/sim_pipeline.s: src/sim_pipeline.cpp.s
.PHONY : src/sim_pipeline.s

# target to generate assembly for a file
src/sim_pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/sim_pipeline.cpp.s
.PHONY : src/sim_pipeline.cpp.s

src/sim_window.o: src/sim_window.cpp.o
.PHONY : src/sim_window.o

# target to build an object file
src/sim_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/sim_window.cpp.o
.PHONY : src/sim_window.cpp.o

src/sim_window.i: src/sim_window.cpp.i
.PHONY : src/sim_window.i

# target to preprocess a source file
src/sim_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/sim_window.cpp.i
.PHONY : src/sim_window.cpp.i

src/sim_window.s: src/sim_window.cpp.s
.PHONY : src/sim_window.s

# target to generate assembly for a file
src/sim_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pastasim.dir/build.make CMakeFiles/pastasim.dir/src/sim_window.cpp.s
.PHONY : src/sim_window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pastasim"
	@echo "... src/application.o"
	@echo "... src/application.i"
	@echo "... src/application.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sim_engine_device.o"
	@echo "... src/sim_engine_device.i"
	@echo "... src/sim_engine_device.s"
	@echo "... src/sim_pipeline.o"
	@echo "... src/sim_pipeline.i"
	@echo "... src/sim_pipeline.s"
	@echo "... src/sim_window.o"
	@echo "... src/sim_window.i"
	@echo "... src/sim_window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/emilh/workspace/physics_sim/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

